#!/bin/sh -e

get_max_gcc_version() {
	for ver in $(seq 5 20); do
		if [ -x "/usr/local/bin/gcc-$ver" ] ; then
			ver1="$ver"
		fi
	done
	echo $ver1
}

PKG_CONFIG_LIBS="libffi libxml2 glib"

for lib in $PKG_CONFIG_LIBS ; do
	if [ -z "$PKG_CONFIG_PATH" ] ; then
		PKG_CONFIG_PATH="/usr/local/opt/$lib/lib/pkgconfig"
	else
		PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/$lib/lib/pkgconfig"
	fi
done

export PKG_CONFIG_PATH

export CFLAGS="-Wno-deprecated -Wno-deprecated-declarations"

GCC_VER="$(get_max_gcc_version)"
if [ -n "$GCC_VER" ] ; then
	CMAKE_OPTS="-DCMAKE_C_COMPILER=gcc-$GCC_VER -DCMAKE_CXX_COMPILER=g++-$GCC_VER"
fi

. CI/travis/make_linux
